A2/urls.py
from django.contrib import admin
from django.urls import path, include
from banks import views 

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.banks_accounts_view, name='home'),# this is my homepage for A2  

    path('banks/', include('banks.urls', namespace='banks')),  

    path('accounts/', include('accounts.urls', namespace='accounts')), 
]

    

accounts/urls.py
from django.urls import path

from .views import register, login_view, logout_view, home, view_profile, edit_profile

app_name = 'accounts' 

urlpatterns = [
    path('register/', register, name='register'),

    path('login/', login_view, name='login'),

    path('logout/', logout_view, name='logout'),

 
    path('', home, name='home'), 

    path('profile/view/', view_profile, name='view_profile'),
    
    path('profile/edit/', edit_profile, name='edit_profile'),
]

banks/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'banks'

urlpatterns = [
    
    path('', views.home, name='home'),

    path('banks_accounts/', views.banks_accounts_view, name='banks_accounts'),

    path('add/', views.add_bank, name='add_bank'),

    path('details/<int:bank_id>/', views.bank_details, name='bank_details'),

    path('<int:bank_id>/branches/add/', views.add_branch, name='add_branch'),

    path('all/', views.list_banks, name='list_banks'),

    path('branch/<int:branch_id>/details/', views.branch_details, name='branch_details'),

    path('details/<int:bank_id>/edit/', views.edit_branch, name='edit_branch'),


]

banks/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.   
#bank
class Bank(models.Model):
    name = models.CharField(max_length=100)
    swift_code = models.CharField(max_length=100)
    institution_number = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

#branch
class Branch(models.Model):
    name = models.CharField(max_length=100)
    transit_number = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    email = models.EmailField(default='admin@utoronto.ca')
    capacity = models.PositiveIntegerField(null=True, blank=True)
    last_modified = models.DateTimeField(auto_now=True)
    bank = models.ForeignKey(Bank, related_name='branches', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

banks/forms.py
from django import forms

from .models import Bank

from .models import Branch

class BankForm(forms.ModelForm):
    class Meta:
        model=Bank
        fields=['name', 'description','institution_number','swift_code',]


class BranchForm(forms.ModelForm):
    class Meta:
        model=Branch
        fields=['name', 'transit_number', 'address', 'email', 'capacity',]

banks/views.py
from django.shortcuts import render,redirect, get_object_or_404

from django.http import JsonResponse, HttpResponse, HttpResponseNotFound, HttpResponseForbidden

from .models import Bank

from .models import Branch

from .forms import BankForm,BranchForm

from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required

from django.urls import reverse

# Create your views here.
@login_required
def add_bank(request):
    if not request.user.is_authenticated:
        return redirect(f'/accounts/login/?next=/banks/add/')
    if request.method == 'POST':
        form = BankForm(request.POST)
        if form.is_valid():
            bank = form.save(commit=False)
            bank.owner = request.user  
            bank.save()
            return redirect(reverse('banks:bank_details', args=[bank.id]))
             #Success URL: /banks/<bank_id>/details/

    else:
        form = BankForm()

    return render(request, 'banks/add.html', {'form': form})

@login_required
def add_branch(request, bank_id):
    bank = get_object_or_404(Bank, id=bank_id)

    if request.method == 'POST':
        form = BranchForm(request.POST)
        if form.is_valid():
            branch = form.save(commit=False)
            branch.bank = bank  
            branch.save()
            return redirect('banks:branch_details', branch_id=branch.id)
    else:
        form = BranchForm()

    return render(request, 'banks/branches/add.html', {'form': form, 'bank': bank})


def banks_accounts_view(request):
   banks = Bank.objects.all()
   branch = Branch.objects.all()
   return render(request, 'banks/banks_accounts.html', {'banks': banks, 'branch': branch})

def home(request):
     return render(request, 'banks/home.html')

def list_banks(request):
    banks = Bank.objects.all()
    return render(request, 'banks/list_banks.html', {'banks': banks})

def bank_details(request, bank_id):
    bank = get_object_or_404(Bank, id=bank_id)
    branches = Branch.objects.filter(bank=bank)
    return render(request, 'banks/details.html', {'bank': bank, 'branches': branches})

@login_required
def branch_details(request, branch_id):
    branch = get_object_or_404(Branch, id=branch_id)
    data = {
        'id': branch.id,
        'name': branch.name,
        'transit_number': branch.transit_number,
        'address': branch.address,
        'email': branch.email,
        'capacity': branch.capacity,
        'last_modified': branch.last_modified.isoformat()
    }
    return JsonResponse(data)

@login_required
def edit_branch(request, bank_id):
    branch = get_object_or_404(Branch, bank_id=bank_id) 
    if request.method == 'POST':
        form = BranchForm(request.POST, instance=branch)
        if form.is_valid():
            form.save()
            return redirect('/branch/detail.html', bank_id=branch.bank_id)  
    else:
        form = BranchForm(instance=branch)
    
    return render(request, 'banks/branch/edit.html', {'form': form})

banks/templates/banks/add.html
{% extends 'banks/home.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'banks/css/styles.css' %}">

    <div class="form-container">
        <a href="{% url 'accounts:logout' %}?next=/banks/" class="button logout-button">Logout</a>
        
        <h1>Create Bank</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="button">Submit</button>
        </form>
    </div>
{% endblock %}

banks/templates/banks/bank_details.html
{% extends 'banks/home.html' %}

{% block content %}
  <h1>{{ bank.name }}</h1>
  <p>Swift Code: {{ bank.swift_code }}</p>
  <p>Institution Number: {{ bank.inst_num }}</p>
  <p>Description: {{ bank.description }}</p>

  <h2>Branches</h2>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Transit Number</th>
        <th>Address</th>
      </tr>
    </thead>
    <tbody>
      {% for branch in branches %}
        <tr>
          <td>{{ branch.name }}</td>
          <td>{{ branch.transit_num }}</td>
          <td>{{ branch.address }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

banks/templates/banks/banks_accounts.html
{% load static %}
<html>
<head>
    <title>Home Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'banks/css/styles.css' %}">
</head>
<body>
    <div class="header-container">
        <h1> Explore the A2 apps:</h1>
    </div>
    
 <div class="form-container">
   
    <h2>Banks App</h2>
    <a href="{% url 'banks:home' %}" class="button">View Banks</a>

 </div>

 <div class="form-container">
        
    <h2>Accounts App</h2>
    <a href="{% url 'accounts:home' %}" class="button">View Accounts</a>
 </div>
    
   
</body>
</html>

banks/templates/banks/details.html
{% extends 'banks/home.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'banks/css/styles.css' %}">


<div class="form-container">
  <h1>{{ bank.name }}</h1>
  <p>Swift Code: {{ bank.swift_code }}</p>
  <p>Institution Number: {{ bank.institution_number }}</p>
  <p>Description: {{ bank.description }}</p>
</div>
<div class="form-container">
  <h2>Branches</h2>
  <a href="{% url 'banks:add_branch' bank_id=bank.id %}" class=button>Add New Branch</a>


  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Transit Number</th>
        <th>Address</th>
      </tr>
    </thead>
    <tbody>
      {% for branch in branches %}
        <tr>
          <td>{{ branch.name }}</td>
          <td>{{ branch.transit_number }}</td>
          <td>{{ branch.address }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="3">No branches available.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>  
{% endblock %}

banks/templates/banks/home.html
{% load static %}
<html>
<head>
    <title>Home</title>
    <link rel="stylesheet" type="text/css" href="{% static 'banks/css/styles.css' %}">
</head>
<body>
    <div class="header-container">
    <h1>Welcome to the Bank App</h1>
    </div>
    {% block content %}

    <div class="form-container">
        <h2> Add Bank</h2>
        <a href="{% url 'banks:add_bank' %}" class="button">Add Bank</a>

    </div>

    <div class="form-container">
        <h2>List of Banks</h2>
        <a href="{% url 'banks:list_banks' %}" class="button">View List</a>
    </div>

    
    
   
   
    {% endblock %}
    

</body>
</html>

banks/templates/banks/list_banks.html
{% extends 'banks/home.html' %}

{% block content %}
<div class="form-container">

  <h1>List of Banks</h1>
 <ul>
 <li><a href="/banks/details/41/">Natiomal Bank</a> 001</li>
 <li><a href="/banks/details/42">BMO</a> 002</li>
 <li><a href="/banks/details/43">TD</a> 003</li>
 </ul>
 </body>
</div>
{% endblock %}